# input files
gvcflist: proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/lists/final_gvcfs.list
reference: /proj/ideel/resources/genomes/Pvivax/genomes/PvP01.fasta
max_alleles: 3
outdir: /pine/scr/n/f/nfb/Projects/VivID_Seq/vcfs_gatk_vsqr/
## SNPs
# TO DO -- should I be filtering to SNPs here?
# known and truth sets for building VQSR model for SNPs
snps_vcf_TP: /pine/scr/n/f/nfb/Projects/VivID_Seq/vcfs_gatk_lab_strains/Pvlabstrains_filtered.vcf.gz
snps_prior_TP: 15
snps_vcf_TPFP: /pine/scr/n/f/nfb/Projects/VivID_Seq/vcfs_gatk_lab_strains/Pvlabstrains_raw.vcf.gz
snps_prior_TPFP: 8
snps_tranches: [ 100.0, 99.9, 99.0, 90.0 ]
snps_ncomponents: 4
snps_input_annotations: [ QD, MQ, MQRankSum, ReadPosRankSum, FS, SOR ]
snps_filter_level: 90.0


## Indels
# known and truth sets for building VQSR model for SNPs


# resource requirements
recal_memory: 16
