---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Phylogenetic Analyses, All Filtered Samples
```{r, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, eval = T, results = 'hide',
                      fig.align = 'center', fig.width = 8, fig.height = 8)
knitr::opts_knit$set(root.dir = here::here())
```


```{r}
library(tidyverse)
library(Biostrings)
library(ape)
library(phangorn)
library(ggtree)
set.seed(48)
```

```{r}
#---------------------------------------------------- 
# Read In
#---------------------------------------------------- 
mtdna <- Biostrings::readDNAStringSet(filepath = "data/fasta/mtdna_anc.fa")


# mtdt and define countries
mtdt <- readRDS("data/derived_data/mtdt.RDS") %>% 
  dplyr::filter(passed == "Y") %>%
  dplyr::mutate(effcountry = ifelse(vividregion == "Lab", "Lab",
                                    ifelse(vividregion == "NHA", "NHA",
                                           country)))



```



### Distance Metrics
```{r}
mtdna.unique.ape <- ape::as.DNAbin(mtdna)

mtdna.dist.JC <- ape::dist.dna(mtdna.unique.ape, model="JC69")
mtdna.dist.n <- ape::dist.dna(mtdna.unique.ape, model="N")
```


```{r, results='asis', fig.width=11, fig.height=8}

# plot
JC69plot <- broom::tidy(mtdna.dist.JC) %>% 
  magrittr::set_colnames(c("smpl1", "smpl2", "dist")) %>% 
  ggplot(data=.) +
  geom_tile(aes(x=smpl1, y=smpl2, fill=dist)) +
  ggtitle("Genetic Distance under Jukes-Cantor's 1969 Model") +
  scale_fill_gradient(low = "#fee0d2", high = "#de2d26") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 5),
        axis.text.x = element_text(angle=90, size = 5),
        axis.title = element_blank(),
        plot.title = element_text(family = "Arial", face = "bold", size = 14, hjust=0.5))
  
pairwiseplot <- broom::tidy(mtdna.dist.n) %>% 
  magrittr::set_colnames(c("smpl1", "smpl2", "dist")) %>% 
  ggplot(data=.) +
  geom_tile(aes(x=smpl1, y=smpl2, fill=dist)) +
  ggtitle("Genetic Pairwise Distance \n (Hammings)") +
  scale_fill_gradient(low = "#fee0d2", high = "#de2d26") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 5),
        axis.text.x = element_text(angle=90, size = 5),
        axis.title = element_blank(),
        plot.title = element_text(family = "Arial", face = "bold", size = 14, hjust=0.5))
  
gridExtra::grid.arrange(JC69plot, pairwiseplot, ncol=2)


```



## MLE for Final Tree
This follows the classic [Felsenstein's 1981 approach](https://link.springer.com/article/10.1007/BF01734359) as outlined by the [phangorn tutorial](https://cran.r-project.org/web/packages/phangorn/vignettes/Trees.pdf).
 

 
### Jukes-Cantor Model Fit
Going to do an MLE tree -- note we boostrap in the backend where we investigate further. 
```{r}
# Phangorn 
mtdna.phangorn <- phangorn::as.phyDat(mtdna.unique.ape)
tree.init <- ape::nj(mtdna.dist.JC)

# JC Model
fitGTR.init <- phangorn::pml(tree.init, mtdna.phangorn, k=4)
fitGTR <- phangorn::optim.pml(fitGTR.init, model = "GTR",
                             optNni=TRUE, optBf=TRUE, optQ=TRUE, optGamma=TRUE)

```



## Pretty Tree
```{r}
#......................
# make prettty tree
#......................
prettdir <- readxl::read_excel("aesthetics/tree_color_decode.xlsx")
tree <- fitGTR$tree
tree <- ape::root(tree, "ERS001838")
tidytree <-  treeio::as.treedata(tree)

# tidy and make tree
treemtdt <- mtdt %>%
  dplyr::mutate(effcountry = ifelse(smpls == "ERS001838", "pcynomolgi", effcountry)) %>%
  dplyr::rename(label = smpls) %>%
  dplyr::select(c("label", "effcountry")) %>%
  dplyr::mutate(treegroup = ifelse(label == "Ebro1944", "Ebro1944",
                                   ifelse(label == "ERS001838", "Pcynomolgi",
                                          ifelse(effcountry == "CD", "DRC", effcountry))))

tidytree <- full_join(tidytree, treemtdt, by = 'label')
tidytree@extraInfo$treegroup[is.na(tidytree@extraInfo$treegroup)] <- "zinternal"
tidytree@extraInfo$treegroup[is.na(tidytree@extraInfo$treegroup)] <- "zinternal"

# make plot
bstree_plotObj <- ggtree(tidytree,
                         branch.length="none",
                         layout="circular",
                         aes(color = treegroup)) +
  geom_tippoint(aes(color =  treegroup, shape = treegroup),
                show.legend = F,
                size = 0.8) +
  scale_color_manual(name = "Country",
                     labels =c("Brazil","China","Colombia","DRC","Ebro1944","Ethiopia","Indonesia" ,"India","Cambodia","Laos","Lab","Sri Lanka",
                               "Madagascar","Myanmar","Mexico","Malaysia","NHA","Pcynomolgi","Peru","Papua New Guinea","Thailand","Vietnam", "zinternal"),
                     values = c(prettdir$hexcolor, "#000000")) +
  scale_shape_manual(name = "Country",
                     labels = c("Brazil","China","Colombia","DRC","Ebro1944","Ethiopia","Indonesia" ,"India","Cambodia","Laos","Lab ","Sri Lanka",
                                "Madagascar","Myanmar","Mexico","Malaysia","NHA","Pcynomolgi","Peru","Papua New Guinea","Thailand","Vietnam", "zinternal"),
                     values =  c(prettdir$shape, 0)) +
  theme_tree() +
  theme(legend.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold"))




```

```{r, results='asis', fig.width=11, fig.height=8, fig.align='center'}
plot(bstree_plotObj)
```

