touch pine/scr/n/f/nfb/Projects/VivID_Seq/cynomolgi_pe/*
touch pine/scr/n/f/nfb/Projects/VivID_Seq/cynomolgi_pe/aln/*
touch pine/scr/n/f/nfb/Projects/VivID_Seq/Ebro1944/*
touch pine/scr/n/f/nfb/Projects/VivID_Seq/Pcynomolgi/pcynomolgi_vars/*
touch pine/scr/n/f/nfb/Projects/VivID_Seq/Pcynomolgi/pcynomolgi_vars/gvcfs/*
touch pine/scr/n/f/nfb/Projects/VivID_Seq/public_pe_seqs/*
touch pine/scr/n/f/nfb/Projects/VivID_Seq/public_se_seqs/*
touch pine/scr/n/f/nfb/Projects/VivID_Seq/public_se_seqs/*
touch /pine/scr/n/f/nfb/Projects/VivID_Seq/vcfs_gatk_joint_raw/chunks/all/*
touch /pine/scr/n/f/nfb/Projects/VivID_Seq/vcfs_hardfilt_variants/*
touch /pine/scr/n/f/nfb/Projects/VivID_Seq/wgs_pe_improved_global/aln/*
touch /pine/scr/n/f/nfb/Projects/VivID_Seq/wgs_se_improved_global/aln/*
touch /pine/scr/n/f/nfb/Projects/VivID_Seq/wgs_pe_improved_ViVIDSmpls/aln/*
touch /pine/scr/n/f/nfb/Projects/VivID_Seq/wgs_qc_improved_global/qc/*
touch /pine/scr/n/f/nfb/Projects/VivID_Seq/wgs_qc_improved_ViVIDSmpls/qc/*
