# configuration for alignment pipeline
reference: /proj/ideel/resources/genomes/Pvivax/genomes/PvP01.fasta

adapters: /nas02/apps/trimmomatic-0.36/Trimmomatic-0.36/adapters/TruSeq3-PE.fa
min_trimmed_length: 30

logs: jobs
tmpdir: .tmp
readbuffer: 1000000
threads: 6
memory: 12

runs: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/Pcynomolgi/cynomolgi_run_map.tab.txt
aligned: aln # go to scratch
fastq: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/Pcynomolgi/fastq
