accessions: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/Pcynomolgi/snakescrape_ENA/cynomolgi_scrape.tab.txt
scratch: /pine/scr/n/f/nfb/Projects/VivID_Seq/cynomolgi_pe/logs/
outputdir: /pine/scr/n/f/nfb/Projects/VivID_Seq/cynomolgi_pe/
