# config file for QC pipeline
reference: /proj/ideel/resources/genomes/Pvivax/genomes/PvP01.fasta
runs: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/wgs_qc_improved_global/sepeglobalvivid_run_map.tab.txt
aligned: /pine/scr/n/f/nfb/Projects/VivID_Seq/wgs_pe_improved_global/aln/merged
regions: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/regions/mtdna.bed
rmd: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/wgs_qc_improved_global/wgs_qc_report.Rmd
min_depth: 4
max_depth: 1000000
min_base_qual: 20
min_mapping_qual: 10
threads: 4
memory: 8
outdir: /pine/scr/n/f/nfb/Projects/VivID_Seq/wgs_qc_improved_global/qc
windows: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/regions/mtdna.bed
