# input files
gvcflist: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/lists/passed_smpls.gvcfs.list
reference: /proj/ideel/resources/genomes/Pvivax/genomes/PvP01.fasta
targets: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/regions/mtdna.bed
OUTDIR: /pine/scr/n/f/nfb/Projects/VivID_Seq/vcfs_vqsr_variants/
# combine vcf inputs
max_alleles: 3
mode: novel

# known and truth sets for building VQSR model
snps_vcf_TP: /pine/scr/n/f/nfb/Projects/VivID_Seq/vcfs_gatk_lab_strains/Pvlabstrains_filtered.vcf.gz
snps_prior_TP: 15
snps_tranches: [ 100.0, 99.9, 99.0, 95.0, 90.0 ]
snps_ncomponents: 2 # max gauss
snps_filter_level: 90.0
min_VSQLOD:
# resource requirements
recal_memory: 24
