accessions: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/scrape_pubseqs/ENA_master_acc_download_map_SE.tab.txt
scratch: /pine/scr/n/f/nfb/Projects/VivID_Seq/public_se_seqs/logs/
outputdir: /pine/scr/n/f/nfb/Projects/VivID_Seq/public_se_seqs/
