accessions: /proj/ideel/meshnick/users/NickB/Projects/VivID_Seq/scrape_pubseqs/ENA_master_acc_download_map_PE.tab.txt
scratch: /pine/scr/n/f/nfb/Projects/VivID_Seq/public_pe_seqs/logs/
outputdir: /pine/scr/n/f/nfb/Projects/VivID_Seq/public_pe_seqs/
